name: Build Frontend and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        CI=false npm run build
        cd ..

    - name: Commit and push new frontend build
      run: |
        git config user.email "ravari.store@gmail.com"
        git config user.name "RAVARI CI"
        git add frontend/build -f
        git diff --staged --quiet && echo "No build changes" || git commit -m "CI: rebuild frontend [skip ci]"
        git push origin HEAD:main
